### PR TITLE
Fix charset mapper

### PR DESCRIPTION
**Pull request by godpan**
CharsetMapper update see mysql doc:
[CharacterSet](https://dev.mysql.com/doc/internals/en/character-set.html#packet-Protocol::CharacterSet)

### CODE REVIEW

**Comment by oshai** [comment]
I am not sure what is the problem that you fixed so if you can clear that up it will be great.

**Comment by godpan** [comment]
When I analyze the mysql packet,the charset value is not same mysql doc make me confused，others will be think so. and in map have same key is not good idea.

**Comment by oshai** [comment]
@godpan - I agree about the same key in the map, it was like that in the original lib, but I will take a look there. About the mapping itself, I am really not sure I fully understand the use case.

**Comment by oshai** [comment]
@godpan - I did a partial change on #55 - let me know if that is enough.

**Comment by godpan** [comment]
I am sorry, did not read the document carefully, 
they can all be expressed as utf-8,i will colse this pr.

**Pull request closed without merging**
