### PR TITLE
Enable DomainSocket support for both mysql and postgresql

### PR DESCRIPTION
**Pull request by andy-yx-chen**

### CODE REVIEW

**Comment by eveyneely** [comment]
Huge thanks to the author of this PR (@andy-yx-chen). This saved my tail yesterday. 🙏

I'm under a tight deadline to finish an app and yesterday (a few days before deadline) I think to myself "I should probably test the deployment to make sure everything works". You know get the DNS straightened out and whatnot. Anyways, I'm planning to deploy my app on GCP via cloud run and connect to cloud sql. Turns out GCP ONLY supports unix socket connection in their serverless environment stuff. I spent almost all of yesterday googling ways around this because jasync does not currently support unix sockets. Turns out the only way around this is to use a private IP / VPC network with a "VPC serverless connector" that costs between $12 and $70 a month (no thanks). Felt like I was hosed. Would either have to rewrite my entire data layer to use hikari or some shit (gross). Or my expected server costs would rise by ~$600 a year just so I could connect to a stupid database (also gross).

ANYWAYS, I found this PR from issue #175, and was able to cobble together a solution that allowed me to use unix sockets. So, I'm now using jasync in production with GCP unix sockets and things are working great so far. Thanks!!

Will explain my solution for any poor soul who was in my predicament yesterday.

1. fork jasync repo and apply these changes to new branch in forked repo (see https://github.com/eveyneely/jasync-sql/pull/1/files for my final change list)
2. use jitpack to point to your newly forked (and updated) repo instead of maven for jasync https://jitpack.io/
3. update application code to use unix socket instead of host when doing your database connection

```kt
fun dbConnectionPool(config: DbConfig): SuspendingConnection {
    return PostgreSQLConnectionBuilder.createConnectionPool {
        if (config.host != null) {
            host = config.host
        }
        database = config.database
        username = config.user
        password = config.password

        if (config.unixSocketFile != null) {
            unixSocket = DomainSocketAddress(config.unixSocketFile)
        }
    }.asSuspending
}
```

(in GCP the config.unixSocketFile would be the string `/cloudsql/<YOUR CONNECTION NAME>/.s.PGSQL.5432`)

I needed to import netty into my app just to use the `DomainSocketAddress` class (I used `netty-all` but I'm sure there's a better subpackage I should be using instead. Or maybe jaysc can export that one class as part of its api. I forget how that all works.)

Anyways I fired it up and crossed my fingers. And what-do-you-know, works like a charm. ✨

Thanks again to the author of this PR. If I ever get some time, I am going to try to come back submit a real PR.
Just wanted to leave this here for anyone else stuck in the same boat I was in yesterday.

**Comment by oshai** [comment]
Thanks for posting that here. A PR in the future will be awesome!
IIRC the main issue was testing it (in CI).

**Comment by czp3009** [comment]
why this awesome PR not merged? we really need it!

**Comment by oshai** [comment]
I can reopen this if you would like. the original reason for not having this merged was lack of testing: https://github.com/jasync-sql/jasync-sql/issues/175#issuecomment-570503687

**Comment by czp3009** [comment]
@oshai Thanks your response!

The feature of unix domain socket is too important(e.g. in GCP AppEngine), I will review the code and resubmit a PR if i can.

**Comment by oshai** [comment]
> @oshai Thanks your response!
> 
> The feature of unix domain socket is too important(e.g. in GCP AppEngine), I will review the code and resubmit a PR if i can.

Thank you!

**Comment by oshai** [comment]
Implemented in #319

**Pull request closed without merging**
