### PR TITLE
Feature/memsql

### PR DESCRIPTION
**Pull request by ratcashdev**
Initial attempt to get jasync-mysql work with memSQL https://www.memsql.com/
Simple statements work, but PreparedStatements have (had) some difficulties. See the discussion here:
https://gitter.im/jasync-sql/support?at=5d5a54acbeba830fffc00284

### CODE REVIEW

**Comment by oshai** [comment]
The tests in  `MemSQLTest` are currently ignored until we figure out a way to start memsql docker in test containers.

**Comment by oshai** [comment]
Fixed the tests. This issue fixed in version 1.0.6.

**Comment by oshai** [comment]
Thanks @ratcashdev !

**Comment by ratcashdev** [comment]
Fantastic. Thank you for the help.

**Pull request merged**
