### PR TITLE
Add connection timeout to the channel to release the resource timely

### PR DESCRIPTION
**Pull request by bytewayio**
Add connection timeout to the source socket to release the socket resource as soon as the connection timeout

### CODE REVIEW

**Comment by oshai** [comment]
@bytewayio - adding this looks like a good idea. a couple of comments:
* ConnectionPoolConfiguration already have a configuration for `connectionCreateTimeout` and I think that should be reused.
* We should probably add that to MySQL as well.
* I am not sure why you omitted the decoder.

**Comment by bytewayio** [comment]
@oshai 
#1 in ConnectionPoolConfiguration, I copied the connection timeout setting to Configuration, I don't know what you meant by reuse the connectionCreateTimeout, but we should remove the connectionTimeout from pool

#2 MySQL is covered, see MySQLConnectionHandler

#3 because the decode is not used, no need to keep it

**Comment by oshai** [comment]
@bytewayio re  comment 1: I don't think it is a good idea to remove it from pool configuration because it gives another safety on top of the connection configuration (helps to make sure pool is clean etc') so we can keep both. I suggest to make it non-nullable and of type Long (or Int) so it will be similar to the type in the pool.

The other points you're correct, I probably missed that.

**Comment by bytewayio** [comment]
@oshai done with making the connectionTimeout as non-nullable and default to 5 seconds (some as the pool configuration)

**Comment by oshai** [comment]
@bytewayio - thanks for the PR!

**Pull request merged**
